apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: auth-api:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: '5432'
        - name: DB_NAME
          value: authdb
        - name: DB_USER
          value: auth
        - name: DB_PASSWORD
          value: auth123
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
